# Generated by Django 6.0 on 2025-12-17 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField(default=False)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='app.place')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('walk', 'Walk'), ('cab', 'Cab'), ('bus', 'Bus')], max_length=10)),
                ('instruction', models.TextField()),
                ('drop_name', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RouteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='What the user thinks the destination is called', max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_submission', to='app.route')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_submissions', to='app.city')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_route_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='app.routestep')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='app.place')),
            ],
            options={
                'unique_together': {('place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RouteStepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('walk', 'Walk'), ('cab', 'Cab'), ('bus', 'Bus')], max_length=10)),
                ('instruction', models.TextField()),
                ('drop_name', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('route_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.routesubmission')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['route_submission', 'order'], name='app_routest_route_s_deef6a_idx')],
                'unique_together': {('route_submission', 'order')},
            },
        ),
    ]
