# Generated by Django 6.0 on 2025-12-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='starting_places',
            field=models.ManyToManyField(related_name='outgoing_routes', to='app.place'),
        ),
        migrations.AddField(
            model_name='routesubmission',
            name='starting_point',
            field=models.ForeignKey(blank=True, help_text='Where the user started from', max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_point_submissions', to='app.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='app.place'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('city', 'canonical_name')},
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'canonical_name'], name='app_place_city_id_10dc09_idx'),
        ),
        migrations.AddIndex(
            model_name='routestep',
            index=models.Index(fields=['route', 'order'], name='app_routest_route_i_0cf6c4_idx'),
        ),
    ]
