# Generated by Django 6.0 on 2025-12-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_route_starting_places_routesubmission_starting_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesubmission',
            name='starting_point_text',
            field=models.CharField(blank=True, help_text='Free-text starting point from the submitter (optional)', max_length=200),
        ),
    ]
