# Generated by Django 5.2.11 on 2026-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_routesubmission_starting_point_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestep',
            name='mode',
            field=models.CharField(choices=[('walk', 'Walk'), ('cab', 'Cab'), ('bus', 'Bus'), ('keke', 'Keke'), ('bike', 'Bike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='routestepsubmission',
            name='mode',
            field=models.CharField(choices=[('walk', 'Walk'), ('cab', 'Cab'), ('bus', 'Bus'), ('keke', 'Keke'), ('bike', 'Bike')], max_length=10),
        ),
    ]
